### ISSUE TITLE
Question: support other password store backends

### ISSUE THREAD

**Issue by foudfou** [DamienCassou/auth-source-pass#98]
Thank you for this great library. I recently read about [PGP being bad](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html) and [somewhat outdated](https://moxie.org/blog/gpg-and-me/). So I tried to switch to [gopass](/gopasspw/gopass) and played with their [experimental libsodium backend](/gopasspw/gopass/blob/master/docs/backends.md#nacl-based-custom-crypto-backend-xc). gopass is supposed to be a drop-in replacement for pass.

Now `auth-source-pass` doesn't work with gopass-with-xc. From a brief look at the code, it looks like auth-source-pass is trying to search the password store by itself making assumptions about the backend store. It could also just rely on the `pass` utility and its "API" instead. For example auth-source-pass assumes all files end with `.gpg` where they end with `.xc` in my store.

I'm well-aware auth-source-pass is meant for the original `pass` utility, which doesn't make it easy for wrappers to find entries (using `tree -P | tail`). And maybe it'd be easier to make another `auth-source-gopass` library altogether ?

**Comment by DamienCassou** [comment]
Sorry for the delay, I'm on vacation and have rare access to a computer.

> Thank you for this great library. I recently read about [PGP being
> bad](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html)
> and [somewhat outdated](https://moxie.org/blog/gpg-and-me/). 


Thank you for the articles, they were great to read. Nevertheless, you
should pay attention not to throw away GnuPG too fast.  Contrary to
many alternatives, it is both free software and has been scrutinized a
lot.  It's very easy to say that alternatives are better because they
are new but only time will tell if they are worth it. Also, above
articles tend to quickly mention many arguments without going deep
into any particular point.


> Now `auth-source-pass` doesn't work with gopass-with-xc. From a
> brief look at the code, it looks like auth-source-pass is trying to
> search the password store by itself making assumptions about the
> backend store. It could also just rely on the `pass` utility and its
> "API" instead.


More than half of auth-source-pass code is meant to match an
auth-source query with a filename in the password store which, AFAIK,
is not part of pass API.


> For example auth-source-pass assumes all files end with `.gpg` where
> they end with `.xc` in my store.


That's no big deal, the code could search for both extensions. Then,
Emacs should get a file handler for .xc files. Anything else?


> I'm well-aware auth-source-pass is
> meant for the original `pass` utility, which doesn't make it easy
> for wrappers to find entries (using `tree -P | tail`). And maybe
> it'd be easier to make another `auth-source-gopass` library
> altogether ?


If it's not too much of a problem, I would like to try having
auth-source-pass taking care of everything.

**Comment by foudfou** [comment]
yes, I agree with most of your points. I still believe auth-source-pass should not try to bypass `pass` though: let it find candidate entries and provide credentials and metadata for auth-source. I.e. let auth-source-pass call the `pass` executable. I agree that there still is some more filtering to do on candidate entries on the elisp side.

That said, it looks like `pass` can not easily integrate with other tools (ex: `pass find` returning a `tree` output which cannot easily be parsed).

Anyways, your call :) Feel free to close this one. Cheers

**Comment by DamienCassou** [comment]
We have a different view on what password-store is.

To you, it seems that `pass` and `gopass` are compatible entry-points to manipulate a password database. It seems that `gopass` developers agree with you because they are implementing several backends to store passwords in different ways.

To me, the filesystem (i.e., `~/.password-store`) is the entry point and `pass` and `gopass` are just one of many ways to get my passwords. It seems that `pass` developers agree with me because (1) `pass` output is for humans not machines and (2) even `password-store.el` [reads the filesystem](https://git.zx2c4.com/password-store/tree/contrib/emacs/password-store.el#n184). Also, the authors of [browserpass](https://github.com/browserpass/browserpass-extension) agree with me because the tool reads from the filesystem directly, not from `pass`.

As a result, I would like to keep `auth-source-pass` independent from `pass`, at least until `pass` authors clearly say that `pass` should be the only entry point to the password store. That being said, I'm not against making `auth-source-pass` compatible with several `gopass` backends, as long as they use the same philosophy of one encrypted file per password and the [same naming scheme](https://github.com/DamienCassou/auth-password-store/blob/master/test/auth-source-pass-tests.el#L392).

**Comment by foudfou** [comment]
Thanks for the clarification. It looks indeed from the project description that pass is meant to be both a gpg-based filesystem and a command. It doesn't seem to favor either one. But I agree the database  spec of the tool is definitely meant to ease integration.
Maybe for the sake of the argument:
* `password-store.el` actually uses `pass` for everything *except* listing passwords (the code line you cite), and gave up on searching (`"Not implemented"`).
* [other reference browser integrations](https://github.com/passff/passff-host/blob/master/src/passff.py) solely rely on `pass`

**Comment by DamienCassou** [comment]
I'm closing this issue as I don't want to receive issues about this project anymore. They should be sent to emacs-core directly.
